### ISSUE TITLE
Duplicate logs in Raspbian

### ISSUE THREAD

**Issue by pchaigno** [awailly/cis-ubuntu-ansible#48]
On a Raspbian (release 2015-05-05), after running the playbook once (with `use_apparmor = False`) and restarting:
- in `/var/log/`, `syslog`, `messages`, `auth.log`, `kern.log` and `user.log` fill up with several warnings/messages that seem to repeat an infinite number of times.
- The rsyslog daemon is using 100% of the CPU.

**Comment by pchaigno** [comment]
Setting `send_rsyslog_remote` to False during the first run fixes the issue.
Looks related to #44 except that I didn't enable AppArmor :confused: 

@awailly Maybe we should set  `send_rsyslog_remote` to False by default...

**Comment by awailly** [comment]
Yes, seems to be in line with #44. I added some documentation in the `default/main.yml` to describe the bug, @paskl47 have to add it in the documentation. The bug is that you have localhost as remote syslog, failing and retrying everytime. It kill the CPU and disk space.

For the `send_rsyslog_remote` suggestion, I had preferred to force the user to have a remote syslog server. However I understand that it may be a very restrictive point. Thus, can you fill a PR with the new default value?

**Comment by pchaigno** [comment]
To do before we close the issue:
- [x] document the bug ;
- [x] save rsyslog logs locally by default.

**Comment by awailly** [comment]
Closed with #54 from @paskl47.
